image: node:14-stretch

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test
  - build
  - develop
  - production

test:
  stage: test
  script:
    - yarn install
#    - npm test:client
#    - npm test:server
#    - npm test:e2e
  services:
    - name: mongo:4
      alias: mongodb-healthequity
      entrypoint: ['mongod', '--bind_ip', '0.0.0.0']
  variables:
    MONGODB_URI: 'mongodb://mongodb-healthequity/healthequity-test'
    NODE_ENV: 'test'

build:
  stage: build
  script:
    - npm install -g gulp
    - yarn install
    - gulp build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

develop:
  type: deploy
  stage: develop
  image: ruby:2
  script:
    - cd dist
    - git init
    - git config user.name "GitLab CI/CD"
    - git config user.email "daniel.pittman@du.edu"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/brianweirdevminesweeper-colorado-devel.git
    - git add .
    - git reset -- client/stats.json
    - git commit -m "GitLab CI Build"
    - git push -f heroku master
  only:
    - develop

production:
  type: deploy
  stage: production
  image: ruby:2
  script:
    - cd dist
    - git init
    - git config user.name "GitLab CI/CD"
    - git config user.email "daniel.pittman@du.edu"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/brianweirdevminesweeper-colorado-prod.git
    - git add .
    - git reset -- client/stats.json
    - git commit -m "GitLab CI Build"
    - git push -f heroku master
  only:
    - master
