version: '2'
volumes:
    brianweirdev-minesweepermongodata:
    brianweirdev-minesweepernodemodules:
services:
    brianweirdev-minesweeper-nodejs:
        build: .
        image: "brianweirdev-minesweeper-nodejs"
        container_name: "brianweirdev-minesweeper-nodejs"
        environment:
            - NODE_ENV=development
            # https://daten-und-bass.io/blog/enabling-hot-reloading-with-vuejs-and-vue-cli-in-docker/
            # https://www.reddit.com/r/docker/comments/jvq92d/need_help_with_angular_hot_reloading/
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/app/brianweirdevminesweeper/:rw
            - ./data/root:/root/:rw
            - brianweirdev-minesweepernodemodules:/app/brianweirdevminesweeper/node_modules/
        ports:
            - 8080:8080
            - 8888:8888
            - 9000:9000
            - 9001:9001
        networks:
            brianweirdevminesweeper:
                aliases:
                    - brianweirdev-minesweeper-nodejs
        depends_on:
            - brianweirdev-minesweeper-mongodb
            - brianweirdev-minesweeper-selenium-chrome
            - brianweirdev-minesweeper-selenium-firefox
    # https://hub.docker.com/_/mongo
    brianweirdev-minesweeper-mongodb:
        image: mongo:4
        container_name: "brianweirdev-minesweeper-mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - brianweirdev-minesweepermongodata:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip 0.0.0.0
        networks:
            brianweirdevminesweeper:
                aliases:
                    - brianweirdev-minesweeper-mongodb
    # https://github.com/SeleniumHQ/docker-selenium/releases
    brianweirdev-minesweeper-selenium-chrome:
        image: selenium/standalone-chrome:3.141.59-zinc
        container_name: "brianweirdev-minesweeper-selenium-chrome"
        ports:
            - 4444:4444
        networks:
            brianweirdevminesweeper:
                aliases:
                    - brianweirdev-minesweeper-selenium-chrome

    # https://github.com/SeleniumHQ/docker-selenium/releases
    brianweirdev-minesweeper-selenium-firefox:
        image: selenium/standalone-firefox:3.141.59
        container_name: "brianweirdev-minesweeper-selenium-firefox"
        ports:
            - 4445:4444
        networks:
            brianweirdevminesweeper:
                aliases:
                    - brianweirdevminesweeper-selenium-firefox
networks:
    brianweirdevminesweeper:
